name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latset
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - id: cache-deps
        name: Cache build dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.OS }}-bun-cache-${{ hashFiles('**/bun/lockb') }}
          restore-keys: |
            ${{ runner.OS }}-bun-cache-
      - id: install-deps
        name: Install dependencies
        run: bun install --production
      - id: build
        name: bun run build
