name: Build
on: 
  pull_request: 
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - id: hash
        name: Hash lockfile
        run: echo "lockb-hash=$(sha1sum ./bun.lockb | head -c 40)" >> $GITHUB_OUTPUT
      - id: cache
        name: Cache build dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{steps.hash.outputs.lockb-hash}}
      - id: install-deps
        name: Install build dependencies
        run: bun install
      - id: build
        name: Build
        run: bun run build
      - id: upload
        name: Upload artifacts
        if: steps.build.outcome == 'success' && github.event.pull_request.base.ref == 'main'
        uses: actions/upload-artifact@v3
        with:
          name: build-pr-${{ github.event.number }}
          path: ./dist
