name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - id: hash
        name: Hash lockfile
        run: echo "lockb-hash=$(sha1sum ./bun.lockb | head -c 40)" >> $GITHUB_OUTPUT
      - id: cache
        name: Cache build dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{steps.hash.outputs.lockb-hash}}
      - id: install-deps
        name: Install build dependencies
        run: bun install
      - id: build
        name: Build
        run: bun run build
      - id: version
        name: Generate semantic version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
      - id: bump
        name: Bump package.json version
        run: npm version --no-git-tag-version ${{ steps.version.outputs.version }}
      - id: commit
        name: Commit and push binaries
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: commit binaries - ${{ steps.version.outputs.version_tag }}"
          add: "./dist/bundle.js"
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          files: |
            ./dist/bundle.js
