name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: download
        name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
      - id: commit
        name: Commit and push binaries
        uses: EndBug/add-and-commit@v9
        with:
          add: './dist/bundle.js'
          default_author: github_actions
          message: 'chore: commit binaries (#${{ github.event.number }})' 
      - id: version
        name: Generate semantic version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          files: |
            ./dist/bundle.js
